### ISSUE TITLE
Installation failed because log directory doesn't exists in Prestashop 1.7

### ISSUE THREAD

**Issue by stevenhartz** [hipay/hipay-enterprise-sdk-prestashop#64]
Hi,
When I want to install the latest version 2.2.5 of your module on a prestashop 1.7.4.0, I have a message in the backoffice that appears to tell me that the installation failed because it could not write the log file at the root of the site. This folder doesn't exist by default in prestashop 1.7.

I created manually the file and the installation is done properly. It might be necessary to manage differently the writing of the logs if one is in 1.7

**Comment by etiennelandais** [comment]
https://github.com/hipay/hipay-enterprise-sdk-prestashop/releases/tag/2.2.6
