### ISSUE TITLE
Redirect ctrl 500 with HOSTED_FIELDS 

### ISSUE THREAD

**Issue by DelecroixQuentin** [hipay/hipay-enterprise-sdk-prestashop#68]
Hi,

Why there are no check on PS version here ? This lead to a 500 because you try to use 16 template instead 17...

https://github.com/hipay/hipay-enterprise-sdk-prestashop/blob/6f6e8858140d28cd95051b1c1da05f7d5e53ad29/src/hipay_enterprise/controllers/front/redirect.php#L183-L188

You just need to do the same thing as below:
```php
$path = (_PS_VERSION_ >= '1.7' ? 'module:' .
        $this->module->name .
        '/views/templates/front/payment/ps17/paymentForm-' . $uxMode . '-17'
        : 'payment/ps16/paymentForm-' . $uxMode . '-16') . '.tpl';
```

**Comment by DelecroixQuentin** [comment]
Plus, in the 17 template, you are using a undefined var:
![image](https://user-images.githubusercontent.com/8830801/107926834-7e41d600-6f76-11eb-9b7a-1f8fbd8a86ba.png)

In the 16 template you generate the link directly in the template like that:
`{$link->getModuleLink('hipay_enterprise', 'redirect', [], true)|escape:'html'}` 
but in 17 you use `action="{$action}"` and in the redirect ctrl you never set `$action`

**Comment by legithubdeaymeric** [comment]
Hi @DelecroixQuentin 

Prestashop 1.7 don't use this file redirect.php for an Hosted Field integration.
This is why there is no test of the prestashop version in this case.

**Comment by DelecroixQuentin** [comment]
Hi @legithubdeaymeric,
It seems that there is another problem in the module so:
![image](https://user-images.githubusercontent.com/8830801/107975184-04324100-6fb8-11eb-8680-5911d479533e.png)

**Comment by legithubdeaymeric** [comment]
@DelecroixQuentin 

Hi, 

We made a new version yesterday
Can you tell us if you still have a problem?

2.13.0 
https://github.com/hipay/hipay-enterprise-sdk-prestashop/releases/tag/2.13.0

**Comment by DelecroixQuentin** [comment]
Hi,
I've already test the new version but the problem is still here, hookPaymentOptions return the card payment option with redirect ctrl as action when we choose hosted_fields.

Thanks for your time btw.
