### ISSUE TITLE
Bad parameter passed in the getTransactionById() function in the case of a cancellation

### ISSUE THREAD

**Issue by axometeam** [hipay/hipay-enterprise-sdk-prestashop#75]
In the ApiHandler, a bad parameter passed in the getTransactionById() function in the case of a cancellation

- **File**  => ApiHandler
- **Line** => 257

**$order->id** passed instead of **$params['transaction_reference']**

**Comment by JBaptisteLvt** [comment]
Hello !
This was fixed in 2.18.0, released on the 06 of March 2023
