### ISSUE TITLE
Error on displayAdminOrder hook

### ISSUE THREAD

**Issue by Lionel-dev** [hipay/hipay-enterprise-sdk-prestashop#79]
Module v2.17.2 for PrestaShop 1.7.5.5 in PHP 7.2.

When I have an order with only one virtual product, the hookDisplayAdminOrder causes an error: 

![image](https://user-images.githubusercontent.com/48990561/219304320-d590702f-b2b5-492b-a85c-a98138a338ab.png)

Following the stackTrace, I realize that the problematic line comes from a DiplayPrice in the smarty file "refund.partial.tpl". After a test, it is line 108, "{displayPrice price=$amountFees currency=$id_currency}".
So I tested to display the content of amountFees and we can see that "$this->order->getShipping()" returns a data, but with most of the values at "NULL" :  

![image](https://user-images.githubusercontent.com/48990561/219304553-ac4ef120-6192-47bd-9f43-fd15a024a573.png)

And so the displayPrice is done on "NULL" and generates an error.

The fact that there is no row created in the "ps_order_carrier" table (virtual product). If we look at the "getShipping" function which is a function of the Order class of Prestashop :

![image](https://user-images.githubusercontent.com/48990561/219306872-9af35cc3-b944-4fe2-b5b9-dd77db6b705d.png)

We see that most of the fields are precisely defined by OC (ps_order_carrier) and C (ps_carrier), and since the query starts from ps_order (which is defined) and the rest of the query uses LEFT JOIN, we will automatically have an array with the keys whose values will be mostly NULL.

Personally, I made a quickfix that fixes my problem, I can always make a pull request to manage this problem.

**Comment by JBaptisteLvt** [comment]
Hello,
I could reproduce the issue, we will be adding the fix to our ROADMAP ASAP :)

**Comment by JBaptisteLvt** [comment]
Hello,
This has been fixed and released in 2.18.0 on the 06 of March 2023
