### ISSUE TITLE
Weird upgrades

### ISSUE THREAD

**Issue by Kaikina** [hipay/hipay-enterprise-sdk-prestashop#87]
Hi, 

I've noticed several problems with your upgrade files.
First of all, 2.18.0 and 2.20.0 are executing the same query, resulting in a SQL exception failing the upgrade. SQL query from 2.20 has to be removed.

Second, the 2.21.4 does not return true at the end of the upgrade, resulting in a fail upgrade.

Thanks.

**Comment by stormwind85** [comment]
Hi @Kaikina !

Thank you so much for reporting this problem !

We fixed the previous upgrade scripts in our new version [2.22.0](https://github.com/hipay/hipay-enterprise-sdk-prestashop/releases/tag/2.22.0) as you indicated.

You are also mentioned in our changelog for your contribution.

Therefore, I will close this issue.

Thanks again !
